CREATE TABLE IF NOT EXISTS role(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);
INSERT INTO role VALUES (1, 'ADMIN');
INSERT INTO role VALUES (2, 'USER');
INSERT INTO role VALUES (3, 'UNKNOWN');